# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3635c07dffcb00d968994be6ac1870df2fe960013cd64340055f75e11c77deeadb4c9b4f10c003f1ba2196da38e35f5eab972229e5e244fcf24c242b26c14d55

test:
  secret_key_base: 7838eeacc0a7650d4e7bb9d3af67f21dd5a76c92a078f05a51eb8b17a181d313d8972f4c225fcc56a7279077788d4b3b3785ee2e8c85421ad165a2b073dbf200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
